version: "3.8"
services:
  postgres:
    image: postgres:10
    container_name: delivery_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    networks:
      - localnet

  app:
    image: delivery0app/delivery:0.0.2
    container_name: delivery_app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/test_db
    depends_on:
      - postgres
    networks:
      - localnet

networks:
  localnet:
    driver: bridge