CREATE TABLE user_table
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    block  BOOLEAN
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE user_role
(
    user_id BIGINT REFERENCES user_table (id),
    role_id BIGINT REFERENCES role (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE courier
(
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR(100) NOT NULL,
    inn            VARCHAR(12)  NOT NULL UNIQUE,
    phone_number   VARCHAR(20)  NOT NULL UNIQUE,
    email          VARCHAR(100) NOT NULL UNIQUE,
    courier_status VARCHAR(50),
    user_id        BIGINT UNIQUE REFERENCES user_table (id) ON DELETE CASCADE
);

CREATE TABLE customer
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20)  NOT NULL UNIQUE,
    email        VARCHAR(100) NOT NULL UNIQUE,
    user_id      BIGINT UNIQUE REFERENCES user_table (id) ON DELETE CASCADE
);

CREATE TABLE order_table
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_address   VARCHAR(100) NOT NULL,
    delivery_address VARCHAR(100) NOT NULL,
    weight           INT CHECK (weight > 0),
    description      VARCHAR(200),
    payment_method   VARCHAR(20)  NOT NULL,
    delivery_date    DATE         NOT NULL,
    order_status     VARCHAR(20)  NOT NULL,
    creation_date    TIMESTAMP    NOT NULL,
    fragile_cargo    BOOLEAN      NOT NULL,
    price            NUMERIC      NOT NULL,
    courier_id       BIGINT       REFERENCES courier (id) ON DELETE SET NULL,
    customer_id      BIGINT       NOT NULL REFERENCES customer (id) ON DELETE SET NULL
);


INSERT INTO role (name) VALUES ('ROLE_COURIER'), ('ROLE_CUSTOMER'), ('ROLE_ADMIN');
